spring:
  application:
    name: hzycloud-dept-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/dept8001
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 1
      max-idle: 1
      max-wait-millis: 3000
      max-total: 5
      initial-size: 3
  jpa:
    show-sql: true
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://hzy:123@localhost:7001/eureka
  instance:
    hostname: localhost:8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
info:
  app.name: hzycloud-dept-service
  company: xxx
  build.artifactId: $project.artifactId$
  build.version: $project.version$